import { CalendarDays } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { createClient } from "@/services/supabase/server";
import { getCurrentMembership } from "@/database/memberships";
import { listAppointments } from "@/database/appointments";
import { AppointmentForm } from "@/features/appointments/form";import { AppointmentActions } from "@/features/appointments/manage-form";
import { createAppointmentAction } from "@/features/appointments/actions";

export default async function AppointmentsPage(){const m=await getCurrentMembership();if(!m)return null;const s=await createClient();const now=new Date();const until=new Date(now);until.setDate(until.getDate()+30);const [{appointments},patients,doctors,services,clinic]=await Promise.all([listAppointments(s,m.organization_id,now.toISOString(),until.toISOString()),s.from("patients").select("id,full_name").eq("organization_id",m.organization_id).eq("is_active",true).order("full_name"),s.from("doctors").select("id,name").eq("organization_id",m.organization_id).eq("is_active",true).eq("availability_status","available").order("name"),s.from("services").select("id,name,duration_minutes").eq("organization_id",m.organization_id).eq("is_active",true).order("name"),s.from("clinics").select("id").eq("organization_id",m.organization_id).maybeSingle()]);return <div className="flex flex-col gap-6"><div><h1 className="font-display text-2xl font-semibold text-ink">Appointments</h1><p className="mt-1 text-sm text-ink-muted">Book, reschedule and manage the next 30 days.</p></div>{clinic.data&&patients.data?.length&&doctors.data?.length&&services.data?.length?<Card><CardHeader><CardTitle>New appointment</CardTitle></CardHeader><CardContent><AppointmentForm action={createAppointmentAction} clinicId={clinic.data.id} patients={patients.data} doctors={doctors.data} services={services.data}/></CardContent></Card>:<Card><CardContent className="flex items-center gap-3 py-8"><CalendarDays size={18}/><p className="text-sm text-ink-muted">Complete clinic, doctor, service and patient setup before booking.</p></CardContent></Card>}<Card><CardHeader><CardTitle>Upcoming</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Start</TableHead><TableHead>Patient</TableHead><TableHead>Doctor</TableHead><TableHead>Service</TableHead><TableHead>Status</TableHead><TableHead>Actions</TableHead></TableRow></TableHeader><TableBody>{appointments.map(a=><TableRow key={a.id}><TableCell>{new Date(a.start_at).toLocaleString()}</TableCell><TableCell>{a.patient_id}</TableCell><TableCell>{a.doctor_id}</TableCell><TableCell>{a.service_id}</TableCell><TableCell>{a.status}</TableCell><TableCell><AppointmentActions appointment={a} doctors={doctors.data??[]}/></TableCell></TableRow>)}{!appointments.length&&<TableRow><TableCell colSpan={6}>No upcoming appointments.</TableCell></TableRow>}</TableBody></Table></CardContent></Card></div>}
