import Link from "next/link";
import { redirect } from "next/navigation";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { logout } from "@/features/auth/actions";
import { saveBusinessProfile } from "@/features/settings/actions";
import { ProfileForm } from "@/features/settings/profile-form";
import { getCurrentMembership } from "@/database/memberships";
export default async function SettingsPage(){const m=await getCurrentMembership();if(!m)redirect("/onboarding");return <div className="flex flex-col gap-6"><div><h1 className="font-display text-2xl font-semibold text-ink">Settings</h1><p className="mt-1 text-sm text-ink-muted">Manage your business configuration and team.</p></div><Card><CardHeader><CardTitle>Business profile</CardTitle></CardHeader><CardContent>{["owner","admin"].includes(m.role)?<ProfileForm action={saveBusinessProfile} initial={{name:m.organization.name,email:m.organization.email??"",phone:m.organization.phone??"",address:m.organization.address??"",country:m.organization.country??"",timezone:m.organization.timezone,currency:m.organization.currency}}/>:<p className="text-sm text-ink-muted">Business profile is read-only for your role.</p>}</CardContent></Card><div className="grid gap-4 sm:grid-cols-2"><SettingLink href="/settings/clinic" title="Clinic & working hours" description="Default duration and weekly schedule."/><SettingLink href="/settings/doctors" title="Doctors" description="Doctors, availability, duration, and archive status."/><SettingLink href="/settings/services" title="Services & pricing" description="Bookable services, prices, duration, and status."/><SettingLink href="/settings/memory" title="Business Memory" description="FAQs, policies, service knowledge, and hours."/><SettingLink href="/settings/team" title="Team" description="Members, invitations, and roles."/></div><Card><CardHeader><CardTitle>Account</CardTitle></CardHeader><CardContent className="flex flex-col gap-4"><p className="text-sm text-ink-muted">Signed in as {m.organization.email ?? "your account"}. Your role is <strong>{m.role}</strong>.</p><form action={logout}><Button type="submit" variant="secondary">Log out</Button></form></CardContent></Card></div>}
function SettingLink({href,title,description}:{href:string;title:string;description:string}){return <Link href={href} className="rounded-lg border border-mist bg-paper-raised p-5 transition-colors hover:border-mist-strong hover:bg-mist/20"><p className="font-medium text-ink">{title}</p><p className="mt-1 text-sm text-ink-muted">{description}</p></Link>}
