"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { createClient } from "@/services/supabase/server";
import { getCurrentMembership } from "@/database/memberships";
import { createAppointment, updateAppointment, cancelAppointment, checkAvailability, verifyAppointmentReferences } from "@/database/appointments";
import type { ActionState } from "@/types";

const schema = z.object({ patientId: z.uuid(), doctorId: z.uuid(), serviceId: z.uuid(), clinicId: z.uuid(), startAt: z.string().datetime({ local: true }), endAt: z.string().datetime({ local: true }), notes: z.string().trim().max(2000) }).superRefine((v, ctx) => { if (new Date(v.endAt) <= new Date(v.startAt)) ctx.addIssue({ code: "custom", path: ["endAt"], message: "End time must be after start time." }); });
async function auth() { const m = await getCurrentMembership(); return m && ["owner","admin","manager","receptionist"].includes(m.role) ? m : null; }
function parse(fd: FormData) { return schema.safeParse({ patientId: fd.get("patientId"), doctorId: fd.get("doctorId"), serviceId: fd.get("serviceId"), clinicId: fd.get("clinicId"), startAt: String(fd.get("startAt") ?? ""), endAt: String(fd.get("endAt") ?? ""), notes: fd.get("notes") }); }
export async function createAppointmentAction(_prev: ActionState, fd: FormData): Promise<ActionState> { const p=parse(fd); if(!p.success)return{fieldErrors:p.error.flatten().fieldErrors}; const m=await auth(); if(!m)return{error:"You do not have permission to manage appointments."}; const s=await createClient(); const validRefs=await verifyAppointmentReferences(s,m.organization_id,{patientId:p.data.patientId,doctorId:p.data.doctorId,serviceId:p.data.serviceId,clinicId:p.data.clinicId}); if(!validRefs)return{error:"Invalid patient, doctor, service, or clinic selected."}; const av=await checkAvailability(s,m.organization_id,p.data.doctorId,new Date(p.data.startAt).toISOString(),new Date(p.data.endAt).toISOString()); if(av.error)return{error:av.error.message}; if(!av.available)return{error:"That doctor is already booked for this time."}; const {error}=await createAppointment(s,{organization_id:m.organization_id,clinic_id:p.data.clinicId,patient_id:p.data.patientId,doctor_id:p.data.doctorId,service_id:p.data.serviceId,start_at:new Date(p.data.startAt).toISOString(),end_at:new Date(p.data.endAt).toISOString(),notes:p.data.notes||null,created_by:(await s.auth.getUser()).data.user?.id??null}); if(error)return{error:error.code==="23P01"?"That time was booked by another request. Choose another slot.":error.message}; revalidatePath("/appointments"); revalidatePath("/dashboard"); return{message:"Appointment booked."}; }
export async function rescheduleAppointmentAction(_prev: ActionState, fd: FormData): Promise<ActionState> { const id=String(fd.get("id")??""); if(!z.uuid().safeParse(id).success)return{error:"Invalid appointment."}; const p=parse(fd); if(!p.success)return{fieldErrors:p.error.flatten().fieldErrors}; const m=await auth(); if(!m)return{error:"You do not have permission to reschedule appointments."}; const s=await createClient(); const validRefs=await verifyAppointmentReferences(s,m.organization_id,{patientId:p.data.patientId,doctorId:p.data.doctorId,serviceId:p.data.serviceId,clinicId:p.data.clinicId}); if(!validRefs)return{error:"Invalid patient, doctor, service, or clinic selected."}; const av=await checkAvailability(s,m.organization_id,p.data.doctorId,new Date(p.data.startAt).toISOString(),new Date(p.data.endAt).toISOString(),id); if(av.error)return{error:av.error.message}; if(!av.available)return{error:"That doctor is already booked for this time."}; const {error}=await updateAppointment(s,m.organization_id,id,{clinic_id:p.data.clinicId,patient_id:p.data.patientId,doctor_id:p.data.doctorId,service_id:p.data.serviceId,start_at:new Date(p.data.startAt).toISOString(),end_at:new Date(p.data.endAt).toISOString(),notes:p.data.notes||null}); if(error)return{error:error.code==="23P01"?"That time was booked by another request.":error.message}; revalidatePath("/appointments"); return{message:"Appointment updated."}; }
export async function cancelAppointmentAction(_prev: ActionState, fd: FormData): Promise<ActionState> { const id=String(fd.get("id")??""); if(!z.uuid().safeParse(id).success)return{error:"Invalid appointment."}; const m=await auth(); if(!m)return{error:"You do not have permission to cancel appointments."}; const s=await createClient(); const {error}=await cancelAppointment(s,m.organization_id,id); if(error)return{error:error.message}; revalidatePath("/appointments"); return{message:"Appointment cancelled."}; }
