"use client";
import { useActionState } from "react";
import { useFormStatus } from "react-dom";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import type { ActionState } from "@/types";
function Submit(){const{pending}=useFormStatus();return <Button type="submit" isLoading={pending}>Book appointment</Button>}
export function AppointmentForm({ action, patients, doctors, services, clinicId }: { action:(p:ActionState,f:FormData)=>Promise<ActionState>; patients:{id:string;full_name:string}[]; doctors:{id:string;name:string}[]; services:{id:string;name:string;duration_minutes:number}[]; clinicId:string }){const[state,formAction]=useActionState(action,null);return <form action={formAction} className="grid gap-4 sm:grid-cols-2"><input type="hidden" name="clinicId" value={clinicId}/><div><Label>Patient</Label><select name="patientId" required className="h-10 w-full rounded-md border border-mist-strong bg-paper-raised px-3 text-sm">{patients.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></div><div><Label>Doctor</Label><select name="doctorId" required className="h-10 w-full rounded-md border border-mist-strong bg-paper-raised px-3 text-sm">{doctors.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div><div><Label>Service</Label><select name="serviceId" required className="h-10 w-full rounded-md border border-mist-strong bg-paper-raised px-3 text-sm">{services.map(x=><option key={x.id} value={x.id}>{x.name} ({x.duration_minutes} min)</option>)}</select></div><div><Label>Start</Label><Input type="datetime-local" name="startAt" required /></div><div><Label>End</Label><Input type="datetime-local" name="endAt" required /></div><div className="sm:col-span-2"><Label>Notes</Label><textarea name="notes" className="min-h-20 w-full rounded-md border border-mist-strong bg-paper-raised p-3 text-sm" /></div><div className="sm:col-span-2 flex gap-3"><Submit/>{state?.error&&<p className="text-sm text-clay">{state.error}</p>}{state?.message&&<p className="text-sm text-ink-muted">{state.message}</p>}</div></form>}
