"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { createClient } from "@/services/supabase/server";
import { createAdminClient } from "@/services/supabase/admin";
import { env } from "@/lib/env";
import crypto from "node:crypto";
import { getCurrentMembership } from "@/database/memberships";
import type { ActionState } from "@/types";

const inviteSchema=z.object({email:z.email().transform(v=>v.toLowerCase()),role:z.enum(["admin","manager","receptionist"])});
async function manageTeam(){const m=await getCurrentMembership();if(!m||!["owner","admin"].includes(m.role))return null;return m;}
export async function inviteMember(_prev:ActionState,fd:FormData):Promise<ActionState>{const p=inviteSchema.safeParse({email:fd.get("email"),role:fd.get("role")});if(!p.success)return{fieldErrors:p.error.flatten().fieldErrors};const m=await manageTeam();if(!m)return{error:"Only owners and admins can invite team members."};const s=await createClient();const {data:existing}=await s.from("memberships").select("id").eq("organization_id",m.organization_id).limit(1);const {data:already}=await s.from("pending_invites").select("id").eq("organization_id",m.organization_id).eq("email",p.data.email).maybeSingle();if(already)return{error:"That email already has a pending invitation."};if(existing?.length===0)return{error:"The organization owner must remain the first member."};const rawToken=crypto.randomBytes(32).toString("hex"); const tokenHash=crypto.createHash("sha256").update(rawToken).digest("hex"); const {data:invite,error}=await s.from("pending_invites").insert({organization_id:m.organization_id,email:p.data.email,role:p.data.role,invited_by:(await s.auth.getUser()).data.user?.id ?? "",token_hash:tokenHash,expires_at:new Date(Date.now()+7*24*60*60*1000).toISOString()}).select().single();if(error||!invite)return{error:error?.message??"Could not create invitation."};const admin=createAdminClient();const {error:inviteError}=await admin.auth.admin.inviteUserByEmail(p.data.email,{redirectTo:`${env.NEXT_PUBLIC_SITE_URL}/auth/confirm?next=${encodeURIComponent(`/invite/accept?token=${rawToken}`)}`});if(inviteError){await s.from("pending_invites").delete().eq("id",invite.id);return{error:inviteError.message};}revalidatePath("/settings/team");return{message:"Invitation sent."};}
export async function cancelInvite(_prev:ActionState,fd:FormData):Promise<ActionState>{const m=await manageTeam();if(!m)return{error:"Only owners and admins can cancel invitations."};const id=String(fd.get("id")??"");if(!z.string().uuid().safeParse(id).success)return{error:"Invalid invitation."};const s=await createClient();const {error}=await s.from("pending_invites").delete().eq("id",id).eq("organization_id",m.organization_id);if(error)return{error:error.message};revalidatePath("/settings/team");return{message:"Invitation cancelled."};}
export async function acceptInvite(_prev:ActionState,fd:FormData):Promise<ActionState>{const m=await getCurrentMembership();if(m){return{message:"You are already a member of an organization."};}const s=await createClient();const {data:{user}}=await s.auth.getUser();if(!user?.email)return{error:"A verified email account is required."};const token=String(fd.get("token")??"");if(!/^[a-f0-9]{64}$/.test(token))return{error:"Invalid invitation."};const tokenHash=crypto.createHash("sha256").update(token).digest("hex");const {error}=await s.rpc("accept_pending_invite",{target_token_hash:tokenHash});if(error)return{error:error.message};revalidatePath("/dashboard");revalidatePath("/onboarding");return{message:"Invitation accepted."};}

export async function changeMemberRole(_prev:ActionState,fd:FormData):Promise<ActionState>{const m=await getCurrentMembership();if(!m||m.role!=="owner")return{error:"Only the owner can change member roles."};const id=String(fd.get("id")??"");const role=String(fd.get("role")??"");if(!z.string().uuid().safeParse(id).success||!z.enum(["owner","admin","manager","receptionist"]).safeParse(role).success)return{error:"Invalid member or role."};const s=await createClient();const {data:target}=await s.from("memberships").select("user_id").eq("id",id).eq("organization_id",m.organization_id).maybeSingle();if(!target)return{error:"Member not found."};if(target.user_id===m.user_id && role!=="owner")return{error:"The owner cannot remove their own owner role."};const {error}=await s.from("memberships").update({role:role as "owner"|"admin"|"manager"|"receptionist"}).eq("id",id).eq("organization_id",m.organization_id);if(error)return{error:error.message};revalidatePath("/settings/team");return{message:"Member role updated."};}

export async function resendInvite(_prev:ActionState,fd:FormData):Promise<ActionState>{const m=await manageTeam();if(!m)return{error:"Only owners and admins can resend invitations."};const id=String(fd.get("id")??"");if(!z.string().uuid().safeParse(id).success)return{error:"Invalid invitation."};const s=await createClient();const {data:invite}=await s.from("pending_invites").select("id,email").eq("id",id).eq("organization_id",m.organization_id).maybeSingle();if(!invite)return{error:"Invitation not found."};const rawToken=crypto.randomBytes(32).toString("hex");const tokenHash=crypto.createHash("sha256").update(rawToken).digest("hex");const {error:updateError}=await s.from("pending_invites").update({token_hash:tokenHash,expires_at:new Date(Date.now()+7*24*60*60*1000).toISOString()}).eq("id",id).eq("organization_id",m.organization_id);if(updateError)return{error:updateError.message};const admin=createAdminClient();const {error}=await admin.auth.admin.inviteUserByEmail(invite.email,{redirectTo:`${env.NEXT_PUBLIC_SITE_URL}/auth/confirm?next=${encodeURIComponent(`/invite/accept?token=${rawToken}`)}`});if(error)return{error:error.message};revalidatePath("/settings/team");return{message:"Invitation resent."};}
