import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "@/types/database";
import type { AIMessage } from "@/ai/types";
import { getAIProvider } from "@/ai/providers";
import { buildAIContext } from "@/ai/context";
import { composeSystemPrompt } from "@/ai/prompts";
import { toolDefinitions } from "@/ai/tools";
import { executeTool } from "@/ai/tools/executor";
import { consumeAIRateLimit, consumeAIOrgRateLimitService } from "@/lib/rate-limit";

type Client=SupabaseClient<Database>;
const MAX_TOOL_LOOPS=4;
const MAX_TOOL_CALLS=8;
export async function runReceptionist(client:Client,organizationId:string,userId:string|undefined,input:{conversationId?:string;patientId?:string;message:string}){const allowed=userId?await consumeAIRateLimit(client,organizationId,userId,60,20):await consumeAIOrgRateLimitService(client,organizationId,60,20);if(!allowed)throw new Error("AI rate limit exceeded.");const started=Date.now();const provider=getAIProvider();const messages:AIMessage[]=[{role:"system",content:composeSystemPrompt(await buildAIContext(client,organizationId,input.conversationId,input.patientId))},{role:"user",content:input.message.slice(0,10000)}];let toolCallsUsed=0;let finalText="";let lastModel:string|undefined;let inputTokens=0;let outputTokens=0;try{for(let loop=0;loop<MAX_TOOL_LOOPS;loop++){const response=await provider.complete({messages,tools:toolDefinitions});lastModel=response.model;inputTokens+=response.inputTokens??0;outputTokens+=response.outputTokens??0;if(response.toolCalls.length===0){finalText=response.text;break;}if(toolCallsUsed+response.toolCalls.length>MAX_TOOL_CALLS)throw new Error("AI tool-call limit exceeded.");messages.push({role:"assistant",content:response.text,toolCalls:response.toolCalls});for(const call of response.toolCalls){const result=await executeTool(client,organizationId,userId,call.name,call.arguments);messages.push({role:"tool",content:JSON.stringify(result).slice(0,12000),toolCallId:call.id,name:call.name});toolCallsUsed++;}if(loop===MAX_TOOL_LOOPS-1)throw new Error("AI orchestration loop limit exceeded.");}if(!finalText)finalText="I’m sorry, I couldn’t complete that request safely.";await client.from("ai_interaction_logs").insert({organization_id:organizationId,user_id:userId??null,conversation_id:input.conversationId??null,provider:provider.name,model:lastModel??null,success:true,latency_ms:Date.now()-started,input_tokens:inputTokens,output_tokens:outputTokens,tool_calls:messages.filter(m=>m.toolCalls).flatMap(m=>m.toolCalls??[]).map(x=>x.name),error_code:null});return{message:finalText,provider:provider.name,model:lastModel};}catch(error){await client.from("ai_interaction_logs").insert({organization_id:organizationId,user_id:userId??null,conversation_id:input.conversationId??null,provider:provider.name,model:lastModel??null,success:false,latency_ms:Date.now()-started,input_tokens:inputTokens,output_tokens:outputTokens,tool_calls:messages.filter(m=>m.toolCalls).flatMap(m=>m.toolCalls??[]).map(x=>x.name),error_code:error instanceof Error?error.name:"AI_ERROR"});throw error;}}
