"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { createClient } from "@/services/supabase/server";
import { getCurrentMembership } from "@/database/memberships";
import { findOrCreateConversation, insertMessage } from "@/database/conversations";
import { runReceptionist } from "@/ai/orchestrator";
import type { ActionState } from "@/types";
const schema=z.object({conversationId:z.uuid().optional(),patientId:z.uuid().optional(),content:z.string().trim().min(1).max(10000)});
export async function sendConversationMessage(_prev:ActionState,fd:FormData):Promise<ActionState>{const p=schema.safeParse({conversationId:fd.get("conversationId")||undefined,patientId:fd.get("patientId")||undefined,content:fd.get("content")});if(!p.success)return{fieldErrors:p.error.flatten().fieldErrors};const m=await getCurrentMembership();if(!m)return{error:"Not authenticated."};const s=await createClient();const user=(await s.auth.getUser()).data.user;if(!user)return{error:"Not authenticated."};let conversationId=p.data.conversationId;if(!conversationId){const c=await findOrCreateConversation(s,{organization_id:m.organization_id,patient_id:p.data.patientId??null,channel:"web_chat",external_contact_key:`staff:${user.id}`});if(c.error||!c.conversation)return{error:c.error?.message??"Could not create conversation."};conversationId=c.conversation.id;}const c=await s.from("conversations").select("id,patient_id").eq("organization_id",m.organization_id).eq("id",conversationId).maybeSingle();if(!c.data)return{error:"Conversation not found."};const {error}=await insertMessage(s,{organization_id:m.organization_id,conversation_id:conversationId,patient_id:c.data.patient_id,sender_type:"human",direction:"outbound",content:p.data.content,delivery_status:"sent"});if(error)return{error:error.message};try{const ai=await runReceptionist(s,m.organization_id,user.id,{conversationId,patientId:c.data.patient_id??undefined,message:p.data.content});await insertMessage(s,{organization_id:m.organization_id,conversation_id:conversationId,patient_id:c.data.patient_id,sender_type:"ai",direction:"outbound",content:ai.message,delivery_status:"sent",metadata:{provider:ai.provider,model:ai.model??null}});}catch{return{error:"Message saved, but the AI response could not be generated."};}revalidatePath(`/conversations/${conversationId}`);revalidatePath("/conversations");return{message:"Message sent."};}
