"use client";

import { useActionState } from "react";
import { useFormStatus } from "react-dom";
import { Button } from "@/components/ui/button";
import { FormField } from "@/components/ui/form-field";
import { Input } from "@/components/ui/input";
import type { ActionState } from "@/types";

function Submit({ children }: { children: React.ReactNode }) { const { pending } = useFormStatus(); return <Button type="submit" isLoading={pending}>{children}</Button>; }
function ErrorBox({ state }: { state: ActionState }) { return state?.error ? <p role="alert" className="rounded-md border border-clay/30 bg-clay/5 p-3 text-sm text-clay">{state.error}</p> : null; }

export function BusinessForm({ action, initial }: { action: (p: ActionState, f: FormData) => Promise<ActionState>; initial: Record<string,string> }) {
  const [state, formAction] = useActionState(action, null);
  return <form action={formAction} className="flex flex-col gap-5"><FormField id="name" label="Business name" errors={state?.fieldErrors?.name}><Input name="name" defaultValue={initial.name} required /></FormField><FormField id="email" label="Business email" errors={state?.fieldErrors?.email}><Input name="email" type="email" defaultValue={initial.email} /></FormField><div className="grid gap-5 sm:grid-cols-2"><FormField id="phone" label="Phone" errors={state?.fieldErrors?.phone}><Input name="phone" defaultValue={initial.phone} /></FormField><FormField id="country" label="Country" errors={state?.fieldErrors?.country}><Input name="country" defaultValue={initial.country} /></FormField></div><FormField id="address" label="Address" errors={state?.fieldErrors?.address}><Input name="address" defaultValue={initial.address} /></FormField><div className="grid gap-5 sm:grid-cols-2"><FormField id="timezone" label="Timezone" errors={state?.fieldErrors?.timezone}><Input name="timezone" defaultValue={initial.timezone || "Asia/Karachi"} required /></FormField><FormField id="currency" label="Currency" errors={state?.fieldErrors?.currency}><Input name="currency" defaultValue={initial.currency || "PKR"} required /></FormField></div><ErrorBox state={state}/><div className="flex justify-end"><Submit>Save & continue</Submit></div></form>;
}

export function ClinicForm({ action, initial }: { action: (p: ActionState, f: FormData) => Promise<ActionState>; initial: number }) { const [state, formAction] = useActionState(action, null); return <form action={formAction} className="flex flex-col gap-5"><FormField id="defaultAppointmentDurationMinutes" label="Default appointment duration (minutes)" errors={state?.fieldErrors?.defaultAppointmentDurationMinutes}><Input name="defaultAppointmentDurationMinutes" type="number" min="1" max="480" defaultValue={initial} required /></FormField><ErrorBox state={state}/><div className="flex justify-end"><Submit>Save & continue</Submit></div></form>; }

export function DoctorForm({ action }: { action: (p: ActionState, f: FormData) => Promise<ActionState> }) { const [state, formAction] = useActionState(action, null); return <form action={formAction} className="grid gap-5 sm:grid-cols-2"><FormField id="name" label="Doctor name" errors={state?.fieldErrors?.name}><Input name="name" required /></FormField><FormField id="specialization" label="Specialization" errors={state?.fieldErrors?.specialization}><Input name="specialization" /></FormField><FormField id="email" label="Email" errors={state?.fieldErrors?.email}><Input name="email" type="email" /></FormField><FormField id="phone" label="Phone" errors={state?.fieldErrors?.phone}><Input name="phone" /></FormField><FormField id="appointmentDurationMinutes" label="Appointment duration (minutes)" errors={state?.fieldErrors?.appointmentDurationMinutes}><Input name="appointmentDurationMinutes" type="number" min="1" max="480" defaultValue="30" required /></FormField><div className="flex items-end"><Submit>Add doctor</Submit></div><div className="sm:col-span-2"><ErrorBox state={state}/></div></form>; }

export function ServiceForm({ action }: { action: (p: ActionState, f: FormData) => Promise<ActionState> }) { const [state, formAction] = useActionState(action, null); return <form action={formAction} className="grid gap-5 sm:grid-cols-2"><FormField id="name" label="Service name" errors={state?.fieldErrors?.name}><Input name="name" required /></FormField><FormField id="price" label="Price (PKR)" errors={state?.fieldErrors?.price}><Input name="price" type="number" min="0" step="0.01" defaultValue="0" required /></FormField><FormField id="durationMinutes" label="Duration (minutes)" errors={state?.fieldErrors?.durationMinutes}><Input name="durationMinutes" type="number" min="1" max="480" defaultValue="30" required /></FormField><FormField id="description" label="Description" errors={state?.fieldErrors?.description}><Input name="description" /></FormField><div className="sm:col-span-2"><ErrorBox state={state}/></div><div className="sm:col-span-2"><Submit>Add service</Submit></div></form>; }
