"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { createClient } from "@/services/supabase/server";
import { getCurrentMembership } from "@/database/memberships";
import { createService, updateService, deleteService } from "@/database/services";
import type { ActionState } from "@/types";
const schema=z.object({name:z.string().trim().min(2).max(150),price:z.coerce.number().nonnegative().max(99999999),duration:z.coerce.number().int().positive().max(480),description:z.string().trim().max(500),active:z.enum(["true","false"]) });
async function allowed(){const m=await getCurrentMembership();if(!m||!["owner","admin","manager"].includes(m.role))return null;return m;}
export async function saveService(_prev:ActionState,fd:FormData):Promise<ActionState>{const p=schema.safeParse({name:fd.get("name"),price:fd.get("price"),duration:fd.get("duration"),description:fd.get("description"),active:fd.get("active")??"true"});if(!p.success)return{fieldErrors:p.error.flatten().fieldErrors};const m=await allowed();if(!m)return{error:"You do not have permission to manage services."};const s=await createClient();const id=String(fd.get("id")??"");const payload={name:p.data.name,price:p.data.price,duration_minutes:p.data.duration,description:p.data.description||null,is_active:p.data.active === "true"};const result=id?await updateService(s,id,payload):await createService(s,{organization_id:m.organization_id,...payload});if(result.error)return{error:result.error.message};revalidatePath("/settings/services");return{message:id?"Service updated.":"Service added."};}
export async function archiveService(_prev:ActionState,fd:FormData):Promise<ActionState>{const m=await allowed();if(!m)return{error:"You do not have permission to manage services."};const id=String(fd.get("id")??"");if(!z.string().uuid().safeParse(id).success)return{error:"Invalid service."};const s=await createClient();const result=await updateService(s,id,{is_active:false});if(result.error)return{error:result.error.message};revalidatePath("/settings/services");return{message:"Service archived."};}
export async function deleteServiceAction(_prev:ActionState,fd:FormData):Promise<ActionState>{const m=await allowed();if(!m)return{error:"You do not have permission to manage services."};const id=String(fd.get("id")??"");if(!z.string().uuid().safeParse(id).success)return{error:"Invalid service."};const s=await createClient();const result=await deleteService(s,id);if(result.error)return{error:result.error.message};revalidatePath("/settings/services");return{message:"Service deleted."};}
