import { requireMembership } from "@/lib/auth/tenant";
import { createClient } from "@/services/supabase/server";
import { listMembersWithEmail } from "@/database/memberships";
import { InviteForm } from "@/features/team/form";
import { cancelInvite, changeMemberRole, inviteMember, resendInvite } from "@/features/team/actions";
import { MemberRoleForm } from "@/features/team/member-role-form";
import { Button } from "@/components/ui/button";
import { ActionForm } from "@/components/ui/action-form";
import { ConfirmDestructiveAction } from "@/components/ui/confirm-destructive-action";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { createAdminClient } from "@/services/supabase/admin";
export default async function TeamPage(){const m=await requireMembership();const s=await createClient();const members=await listMembersWithEmail(s,m.organization_id);const admin=createAdminClient();const {data:invites}=await admin.from("pending_invites").select("id,email,role,created_at").eq("organization_id",m.organization_id).order("created_at",{ascending:false});const canManage=m.role==="owner"||m.role==="admin";return <div className="flex flex-col gap-6"><div><h1 className="font-display text-2xl font-semibold text-ink">Team</h1><p className="mt-1 text-sm text-ink-muted">Manage who can access this organization.</p></div>{canManage&&<Card><CardHeader><CardTitle>Invite a member</CardTitle></CardHeader><CardContent><InviteForm action={inviteMember}/></CardContent></Card>}<Card><CardHeader><CardTitle>Members</CardTitle></CardHeader><CardContent>{members.length?<Table><TableHeader><TableRow><TableHead>Email</TableHead><TableHead>Role</TableHead><TableHead>Joined</TableHead></TableRow></TableHeader><TableBody>{members.map(member=><TableRow key={member.id}><TableCell>{member.email}</TableCell><TableCell><MemberRoleForm action={changeMemberRole} id={member.id} role={member.role} disabled={m.role!=="owner"}/></TableCell><TableCell>{new Date(member.created_at).toLocaleDateString()}</TableCell></TableRow>)}</TableBody></Table>:<p className="text-sm text-ink-muted">No team members yet.</p>}</CardContent></Card>{canManage&&<Card><CardHeader><CardTitle>Pending invitations</CardTitle></CardHeader><CardContent>{invites?.length?<div className="space-y-3">{invites.map(invite=><div key={invite.id} className="flex flex-wrap items-center justify-between gap-3 rounded-md border border-mist p-3"><div><p className="text-sm font-medium text-ink">{invite.email}</p><p className="text-xs text-ink-muted">{invite.role} · {new Date(invite.created_at).toLocaleDateString()}</p></div><div className="flex gap-2"><ActionForm action={resendInvite}><input type="hidden" name="id" value={invite.id}/><Button type="submit" size="sm" variant="secondary">Resend</Button></ActionForm><ConfirmDestructiveAction action={cancelInvite} triggerLabel="Cancel" confirmLabel="Cancel invitation" title="Cancel this invitation?" description={`${invite.email} won't be able to use this invite link anymore.`}><input type="hidden" name="id" value={invite.id}/></ConfirmDestructiveAction></div></div>)}</div>:<p className="text-sm text-ink-muted">No pending invitations.</p>}</CardContent></Card>}</div>}
