"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { createClient } from "@/services/supabase/server";
import { getCurrentMembership } from "@/database/memberships";
import { createDoctor, updateDoctor, deleteDoctor } from "@/database/doctors";
import type { ActionState } from "@/types";
const schema = z.object({ name:z.string().trim().min(2).max(150), specialization:z.string().trim().max(120), email:z.union([z.literal(""),z.email()]), phone:z.string().trim().max(30), duration:z.coerce.number().int().positive().max(480), availability:z.enum(["available","unavailable"]), active:z.enum(["true","false"]) });
async function allowed(){const m=await getCurrentMembership(); if(!m||!["owner","admin","manager"].includes(m.role)) return null; return m;}
export async function saveDoctor(_prev:ActionState, fd:FormData):Promise<ActionState>{const parsed=schema.safeParse({name:fd.get("name"),specialization:fd.get("specialization"),email:fd.get("email"),phone:fd.get("phone"),duration:fd.get("duration"),availability:fd.get("availability")??"available",active:fd.get("active")??"true"});if(!parsed.success)return{fieldErrors:parsed.error.flatten().fieldErrors};const m=await allowed();if(!m)return{error:"You do not have permission to manage doctors."};const s=await createClient();const id=String(fd.get("id")??"");const payload={name:parsed.data.name,specialization:parsed.data.specialization||null,email:parsed.data.email||null,phone:parsed.data.phone||null,appointment_duration_minutes:parsed.data.duration,availability_status:parsed.data.availability,is_active:parsed.data.active === "true"};const result=id?await updateDoctor(s,id,payload):await createDoctor(s,{organization_id:m.organization_id,...payload});if(result.error)return{error:result.error.message};revalidatePath("/settings/doctors");return{message:id?"Doctor updated.":"Doctor added."};}
export async function archiveDoctor(_prev:ActionState,fd:FormData):Promise<ActionState>{const m=await allowed();if(!m)return{error:"You do not have permission to manage doctors."};const id=String(fd.get("id")??"");if(!z.string().uuid().safeParse(id).success)return{error:"Invalid doctor."};const s=await createClient();const result=await updateDoctor(s,id,{is_active:false,availability_status:"unavailable"});if(result.error)return{error:result.error.message};revalidatePath("/settings/doctors");return{message:"Doctor archived."};}
export async function deleteDoctorAction(_prev:ActionState,fd:FormData):Promise<ActionState>{const m=await allowed();if(!m)return{error:"You do not have permission to manage doctors."};const id=String(fd.get("id")??"");if(!z.string().uuid().safeParse(id).success)return{error:"Invalid doctor."};const s=await createClient();const result=await deleteDoctor(s,id);if(result.error)return{error:result.error.message};revalidatePath("/settings/doctors");return{message:"Doctor deleted."};}

const hoursSchema = z.record(z.string(), z.object({ open: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/), close: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/), closed: z.boolean() })).refine((value) => Object.values(value).every((d) => d.closed || d.open < d.close), "Closing time must be after opening time.");
export async function saveDoctorHours(_prev:ActionState,fd:FormData):Promise<ActionState>{const m=await allowed();if(!m)return{error:"You do not have permission to manage doctors."};const id=String(fd.get("doctorId")??"");if(!z.string().uuid().safeParse(id).success)return{error:"Invalid doctor."};const parsed=hoursSchema.safeParse(Object.fromEntries(["mon","tue","wed","thu","fri","sat","sun"].map(day=>[day,{open:String(fd.get(`${day}Open`)??""),close:String(fd.get(`${day}Close`)??""),closed:fd.get(`${day}Closed`)==="on"}])));if(!parsed.success)return{error:parsed.error.issues[0]?.message??"Invalid working hours."};const s=await createClient();const result=await updateDoctor(s,id,{working_hours:parsed.data});if(result.error)return{error:result.error.message};revalidatePath("/settings/doctors");return{message:"Doctor working hours saved."};}
